# Generated by Django 4.2 on 2025-11-11 04:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Stock Keeping Unit - High cardinality unique identifier', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Searchable product name', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the product is active - Low cardinality')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Product creation timestamp')),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(help_text='Product category - Medium cardinality', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'name'], name='products_ca_is_acti_5a5180_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category', 'price', 'created_at'], name='idx_product_search_optimized'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='idx_product_sku'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='idx_product_name'),
        ),
    ]
