# Generated by Django 4.2 on 2025-11-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='idx_product_search_optimized',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='idx_category_search',
            old_name='products_ca_is_acti_5a5180_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category', '-created_at'], name='idx_product_category_sort'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'price'], name='idx_product_price_range'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['category', '-created_at'], name='idx_active_products'),
        ),
    ]
