# Generated by Django 4.2 on 2025-11-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_idx_product_search_optimized_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='idx_active_products',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='idx_category_active_name',
            old_name='idx_category_search',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='idx_product_search_optimized',
            old_name='idx_product_category_sort',
        ),
    ]
